name: Build and Push to DockerHub

on:
  push:
    branches: [ main ]
    tags:     [ 'v*.*.*' ]  # Optional: triggers also on tag pushes

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag or fallback
        id: get_tag
        run: |
          # Default to "latest"
          echo "tags=latest" >> $GITHUB_OUTPUT

          # If running from a Git tag (e.g., v1.2.3), add that too
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            version_tag="${GITHUB_REF##*/}"
            echo "tags=latest,${version_tag}" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            aavotins/hiqbiodiv-container:latest
            ${{ startsWith(github.ref, 'refs/tags/v') && format('aavotins/hiqbiodiv-container:{0}', github.ref_name) || '' }}
